import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'services/hive_service.dart';
import 'services/connectivity_service.dart';
import 'services/sync_service.dart';
import 'services/push_notification_service.dart';

// The UI (screens, theme, navigation, state) is the frontend teammate's work
// and lives in lib/frontend/. This file only starts the backend services and
// then launches that UI.
import 'frontend/app.dart';

late final SyncService syncService;
late final ConnectivityService connectivityService;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await HiveService.init();

  connectivityService = ConnectivityService();
  syncService = SyncService(connectivityService: connectivityService);
  syncService.startListening(); // auto-sync on reconnect, Phase 10

  // Push notifications (replaces SMS): background handler + permission + device token.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  PushNotificationService.instance.init(); // not awaited: do not block app start

  runApp(const GALaundryAppContainer());
}